In [21]:
import numpy as np
m = np.matrix('1 2 3; 4 5 6; 7 8 9')
n = 2 * m
n[n > 10]=0
print(n)

[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


In [43]:
import numpy as np
 
np.random.seed(42)  
arr = np.random.randint(1, 101, 20)
mask = arr % 5 == 0
print ("Числа, которые делятся на 5 без остатка:", arr[mask])
arr[mask] = -1

print ("Обновленный массив:", arr)


Числа, которые делятся на 5 без остатка: [ 15  75  75 100  30]
Обновленный массив: [52 93 -1 72 61 21 83 87 -1 -1 88 -1 24  3 22 53  2 88 -1 38]


In [45]:
import numpy as np

np.random.seed(42)
arr1 = np.random.randint(0, 51, 5)
arr2 = np.random.randint(0, 51, 5)

merged_array = np.vstack((arr1, arr2))

split_array1, split_array2 = np.vsplit(merged_array, 2)

print("Первый массив:", arr1)
print("Второй массив:", arr2)
print("Объединенный массив:\n", merged_array)
print("Разделенные массивы:\n", split_array1, "\n", split_array2)


Первый массив: [38 28 14 42  7]
Второй массив: [20 38 18 22 10]
Объединенный массив:
 [[38 28 14 42  7]
 [20 38 18 22 10]]
Разделенные массивы:
 [[38 28 14 42  7]] 
 [[20 38 18 22 10]]


In [47]:
import numpy as np

arr = np.linspace(-10, 10, 50, dtype=int)

total_sum = np.sum(arr)
positive_sum = np.sum(arr[arr > 0])
negative_sum = np.sum(arr[arr < 0])

print("Сгенерированный массив:", arr)
print("Сумма всех элементов:", total_sum)
print("Сумма положительных элементов:", positive_sum)
print("Сумма отрицательных элементов:", negative_sum)

Сгенерированный массив: [-10 -10 -10  -9  -9  -8  -8  -8  -7  -7  -6  -6  -6  -5  -5  -4  -4  -4
  -3  -3  -2  -2  -2  -1  -1   0   0   1   1   1   2   2   3   3   3   4
   4   5   5   5   6   6   7   7   7   8   8   9   9  10]
Сумма всех элементов: -24
Сумма положительных элементов: 116
Сумма отрицательных элементов: -140


In [49]:
import numpy as np

m_idnt = np.identity(4)

m_diag = np.diag([5, 10, 15, 20])

sum_idnt = np.sum(m_idnt)
sum_diag = np.sum(m_diag)

print("Единичная матрица:\n", m_idnt)
print("Диагональная матрица:\n", m_diag)
print("Сумма элементов единичной матрицы:", sum_idnt)
print("Сумма элементов диагональной матрицы:", sum_diag)

if sum_idnt > sum_diag:
    print("Сумма элементов единичной матрицы больше.")
elif sum_idnt < sum_diag:
    print("Сумма элементов диагональной матрицы больше.")
else:
    print("Суммы элементов матриц равны.")


Единичная матрица:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Диагональная матрица:
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма элементов единичной матрицы: 4.0
Сумма элементов диагональной матрицы: 50
Сумма элементов диагональной матрицы больше.


In [3]:
import numpy as np

np.random.seed(42)
arr1 = np.random.randint(1, 21, (3, 3))
arr2 = np.random.randint(1, 21, (3, 3))

matrix_sum = arr1 + arr2
matrix_diff = arr1 - arr2
matrix_product = arr1 * arr2

print("Первая матрица:\n", arr1)
print("Вторая матрица:\n", arr2)
print("Сумма матриц:\n", matrix_sum)
print("Разность матриц:\n", matrix_diff)
print("Поэлементное произведение:\n", matrix_product)


Первая матрица:
 [[ 7 20 15]
 [11  8  7]
 [19 11 11]]
Вторая матрица:
 [[ 4  8  3]
 [ 2 12  6]
 [ 2  1 12]]
Сумма матриц:
 [[11 28 18]
 [13 20 13]
 [21 12 23]]
Разность матриц:
 [[ 3 12 12]
 [ 9 -4  1]
 [17 10 -1]]
Поэлементное произведение:
 [[ 28 160  45]
 [ 22  96  42]
 [ 38  11 132]]


In [5]:
import numpy as np

np.random.seed(42)
arr1 = np.random.randint(1, 11, (2, 3))
arr2 = np.random.randint(1, 11, (3, 2))

matrix_product = arr1 @ arr2

print("Первая матрица (2×3):\n", arr1)
print("Вторая матрица (3×2):\n", arr2)
print("Результат матричного умножения (2×2):\n", matrix_product)


Первая матрица (2×3):
 [[ 7  4  8]
 [ 5  7 10]]
Вторая матрица (3×2):
 [[3 7]
 [8 5]
 [4 8]]
Результат матричного умножения (2×2):
 [[ 85 133]
 [111 150]]


In [7]:
import numpy as np

np.random.seed(42)
matrix = np.random.randint(1, 11, (3, 3))

# Определитель
determinant = np.linalg.det(matrix)

# Обратная матрица
if np.isclose(determinant, 0):
    inverse_matrix = "Матрица вырождена, обратной матрицы не существует."
else:
    inverse_matrix = np.linalg.inv(matrix)


print("Исходная матрица:\n", matrix)
print("Определитель матрицы:", determinant)
print("Обратная матрица:\n", inverse_matrix)


Исходная матрица:
 [[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]]
Определитель матрицы: -26.000000000000014
Обратная матрица:
 [[ 0.53846154 -0.92307692  0.61538462]
 [ 0.38461538 -1.23076923  1.15384615]
 [-0.53846154  1.42307692 -1.11538462]]


In [9]:
import numpy as np

np.random.seed(42)
matrix = np.random.randint(1, 51, (4, 4))

transposed_matrix = matrix.T

trace_value = np.trace(matrix)

print("Исходная матрица:\n", matrix)
print("Транспонированная матрица:\n", transposed_matrix)
print("След матрицы:", trace_value)

Исходная матрица:
 [[39 29 15 43]
 [ 8 21 39 19]
 [23 11 11 24]
 [36 40 24  3]]
Транспонированная матрица:
 [[39  8 23 36]
 [29 21 11 40]
 [15 39 11 24]
 [43 19 24  3]]
След матрицы: 74


In [11]:
import numpy as np

A = np.array([[2, 3, -1],
              [4, -1, 2],
              [-3, 5, 4]])

B = np.array([5, 6, -2])

solution = np.linalg.solve(A, B)

print("Решение системы (x, y, z):", solution)


Решение системы (x, y, z): [1.63963964 0.57657658 0.00900901]


In [19]:
import numpy as np

# x - первый резервуар, y - второй резервуар, z - третий резервуар

A = np.array([[1, -2, 0],
              [0, -1, 1],
              [1, 1, 1]])

B = np.array([0, 50, 500])

solution_matrix = np.linalg.solve(A, B)

# Метод Крамера
det_A = np.linalg.det(A)
# Определители для метода Крамера
A1 = A.copy()
A1[:, 0] = B
det_A1 = np.linalg.det(A1)

A2 = A.copy()
A2[:, 1] = B
det_A2 = np.linalg.det(A2)

A3 = A.copy()
A3[:, 2] = B
det_A3 = np.linalg.det(A3)

x_kramer = det_A1 / det_A
y_kramer = det_A2 / det_A
z_kramer = det_A3 / det_A

solution_kramer = np.array([x_kramer, y_kramer, z_kramer])


print("Решение методом матриц (np.linalg.solve):", solution_matrix)
print("Решение методом Крамера:", solution_kramer)


Решение методом матриц (np.linalg.solve): [225.  112.5 162.5]
Решение методом Крамера: [225.  112.5 162.5]


In [21]:
import numpy as np

A = np.array([[1, 2, 3], 
              [4, 5, 6]])

k = 3  # Число, на которое умножаем

result = A * k

print(result)


[[ 3  6  9]
 [12 15 18]]


In [23]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[6, 5, 4],
              [3, 2, 1]])

sum_matrix = np.add(A, B)

diff_matrix = np.subtract(A, B)

print("Сумма через np.add():\n", sum_matrix)
print("Разность через np.subtract():\n", diff_matrix)


Сумма через np.add():
 [[7 7 7]
 [7 7 7]]
Разность через np.subtract():
 [[-5 -3 -1]
 [ 1  3  5]]


In [25]:
import numpy as np

A = np.array([[2, -1, 3], 
              [1,  1, 1], 
              [3, -3, 2]])

# Вектор правой части
B = np.array([5, 6, 2])

# Вычисляем определитель
det_A = np.linalg.det(A)

# Проверяем, существует ли единственное решение
if np.isclose(det_A, 0):
    print("Система не имеет единственного решения")
else:
    # Вычисляем детерминанты A_i (заменяя столбцы)
    A1, A2, A3 = A.copy(), A.copy(), A.copy()
    A1[:, 0], A2[:, 1], A3[:, 2] = B, B, B

    det_A1, det_A2, det_A3 = np.linalg.det(A1), np.linalg.det(A2), np.linalg.det(A3)

    # Вычисляем значения x, y, z
    x = det_A1 / det_A
    y = det_A2 / det_A
    z = det_A3 / det_A

    print("Решение методом Крамера:", [x, y, z])


Решение методом Крамера: [2.7777777777777803, 2.555555555555557, 0.6666666666666672]


In [27]:
import numpy as np

A = np.array([[2, -1, 3], 
              [1,  1, 1], 
              [3, -3, 2]])

# Вектор правой части
B = np.array([5, 6, 2])

# Проверяем, можно ли найти обратную матрицу
if np.linalg.det(A) == 0:
    print("Система не имеет единственного решения")
else:
    # Вычисляем обратную матрицу
    A_inv = np.linalg.inv(A)

    # Находим решение
    X = A_inv @ B

    print("Решение матричным методом:", X)


Решение матричным методом: [2.77777778 2.55555556 0.66666667]
