In [5]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b
print(result)

[5 7 9]


In [7]:
import numpy as np
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [9]:
import numpy as np
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
cols = [0, 1, 3]
m[:, cols]
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [17]:
import numpy as np
a = np.random.rand(10)
a
np.where(a > 0.5, True, False)
np.where(a > 0.5, 1, -1)

array([ 1,  1,  1, -1,  1,  1, -1, -1, -1, -1])

In [19]:
x = np.linspace(0, 1, 5)
x
y = np.linspace(0, 2, 5)
y

array([0. , 0.5, 1. , 1.5, 2. ])

In [23]:
xg, yg = np.meshgrid(x, y)
xg

array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ]])

In [25]:
yg

array([[0. , 0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [1. , 1. , 1. , 1. , 1. ],
       [1.5, 1.5, 1.5, 1.5, 1.5],
       [2. , 2. , 2. , 2. , 2. ]])

In [27]:
import matplotlib.pyplot as plt
%matplotlib inline

In [29]:
plt.plot(xg, yg, color="r", marker="*", linestyle="none")

In [31]:
m_sqr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
m_sqr_arr = np.array(m_sqr)
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
A = np.matrix('1 2 3; 4 5 6')
print(A)


[[1 2 3]
 [4 5 6]]


In [35]:
R = (A.T).T
print(R)

[[1 2 3]
 [4 5 6]]


In [37]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8 9; 0 7 5')
L = (A + B).T
R = A.T + B.T
print(L)


[[ 8  4]
 [10 12]
 [12 11]]


In [39]:
print(R)

[[ 8  4]
 [10 12]
 [12 11]]


In [41]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)


[[19 43]
 [22 50]]


In [43]:
print(R)

[[19 43]
 [22 50]]


In [45]:
A = np.matrix('1 2 3; 4 5 6')
k = 3
L = (k * A).T
R = k * (A.T)
print(L)


[[ 3 12]
 [ 6 15]
 [ 9 18]]


In [47]:
print(R)

[[ 3 12]
 [ 6 15]
 [ 9 18]]


In [49]:
A = np.matrix('1 2; 3 4')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(f"{A_det:.9f}")


-2.000000000


In [51]:
print(f"{A_T_det:.9f}")

-2.000000000


In [53]:
A = np.matrix('1 2; 3 4')
L = 1 * A
R = A
print(L)


[[1 2]
 [3 4]]


In [55]:
print(R)

[[1 2]
 [3 4]]


In [57]:
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0')
L = 0 * A
R = Z
print(L)



[[0 0]
 [0 0]]


In [59]:
print(R)

[[0 0]
 [0 0]]


In [3]:
import numpy as np
A = np.matrix('1 2; 3 4')
p = 2
q = 3
L = (p + q) * A
R = p * A + q * A
print(L)


[[ 5 10]
 [15 20]]


In [5]:
print(R)

[[ 5 10]
 [15 20]]


In [7]:
import numpy as np
A = np.matrix('1 2; 3 4')
p = 2
q = 3
L = (p * q) * A
R = p * (q * A)
print(L)

[[ 6 12]
 [18 24]]


In [9]:
print(R)

[[ 6 12]
 [18 24]]


In [11]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
k = 3
L = k * (A + B)
R = k * A + k * B
print(L)

[[18 24]
 [30 36]]


In [13]:
print(R)

[[18 24]
 [30 36]]


In [15]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)

[[192 252]
 [436 572]]


In [17]:
print(R)

[[192 252]
 [436 572]]


In [19]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)


[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [21]:
B = np.matrix('10 4 -1; -4 -1 2; 8 3 1')
print(B)

[[10  4 -1]
 [-4 -1  2]
 [ 8  3  1]]


In [23]:
round(np.linalg.det(A), 3)

-14.0

In [25]:
round(np.linalg.det(B), 3)

14.0

In [27]:
A = np.matrix('1 -3; 2 5')
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.45454545  0.27272727]
 [-0.18181818  0.09090909]]


In [29]:
m_eye = np.eye(4)
print(m_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
rank = np.linalg.matrix_rank(m_eye)
print(rank)

4
