# Лабораторная работа №2
Вариант 6
## Задание 1 практической работы
Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. 
Умножьте все элементы массива на 2, а затем замените все элементы больше 10 на 0. 
Выведите итоговый массив.

In [21]:
import numpy as np
m = np.matrix('1 2 3; 4 5 6; 7 8 9')
n = 2 * m
n[n > 10]=0
print(n)

[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


## Задание 2 практической работы
Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. 
Найдите и выведите все элементы, которые делятся на 5 без остатка. 
Затем замените их на -1 и выведите обновленный массив.

In [43]:
import numpy as np
 
np.random.seed(42)  
arr = np.random.randint(1, 101, 20)
mask = arr % 5 == 0
print ("Числа, которые делятся на 5 без остатка:", arr[mask])
arr[mask] = -1

print ("Обновленный массив:", arr)


Числа, которые делятся на 5 без остатка: [ 15  75  75 100  30]
Обновленный массив: [52 93 -1 72 61 21 83 87 -1 -1 88 -1 24  3 22 53  2 88 -1 38]


## Задание 3 практической работы
Создайте два массива NumPy размером 1×5, заполненные случайными числами от 0 до 50. 
Объедините эти массивы в один двумерный массив (по строкам).
Разделите полученный массив на два массива, каждый из которых содержит 5 элементов.


In [45]:
import numpy as np

np.random.seed(42)
arr1 = np.random.randint(0, 51, 5)
arr2 = np.random.randint(0, 51, 5)

merged_array = np.vstack((arr1, arr2))

split_array1, split_array2 = np.vsplit(merged_array, 2)

print("Первый массив:", arr1)
print("Второй массив:", arr2)
print("Объединенный массив:\n", merged_array)
print("Разделенные массивы:\n", split_array1, "\n", split_array2)


Первый массив: [38 28 14 42  7]
Второй массив: [20 38 18 22 10]
Объединенный массив:
 [[38 28 14 42  7]
 [20 38 18 22 10]]
Разделенные массивы:
 [[38 28 14 42  7]] 
 [[20 38 18 22 10]]


## Задание 4 практической работы
Создайте массив из 50 чисел, равномерно распределенных от -10 до 10. 
Вычислите сумму всех элементов, сумму положительных элементов и сумму отрицательных элементов. 
Выведите результаты.

In [47]:
import numpy as np

arr = np.linspace(-10, 10, 50, dtype=int)

total_sum = np.sum(arr)
positive_sum = np.sum(arr[arr > 0])
negative_sum = np.sum(arr[arr < 0])

print("Сгенерированный массив:", arr)
print("Сумма всех элементов:", total_sum)
print("Сумма положительных элементов:", positive_sum)
print("Сумма отрицательных элементов:", negative_sum)

Сгенерированный массив: [-10 -10 -10  -9  -9  -8  -8  -8  -7  -7  -6  -6  -6  -5  -5  -4  -4  -4
  -3  -3  -2  -2  -2  -1  -1   0   0   1   1   1   2   2   3   3   3   4
   4   5   5   5   6   6   7   7   7   8   8   9   9  10]
Сумма всех элементов: -24
Сумма положительных элементов: 116
Сумма отрицательных элементов: -140


## Задание 5 практической работы
Создайте: Единичную матрицу размером 4×4. 
Диагональную матрицу размером 4×4 с диагональными элементами [5, 10, 15,20] (не использовать циклы). 
Найдите сумму всех элементов каждой из этих матриц и сравните результаты.


In [49]:
import numpy as np

m_idnt = np.identity(4)

m_diag = np.diag([5, 10, 15, 20])

sum_idnt = np.sum(m_idnt)
sum_diag = np.sum(m_diag)

print("Единичная матрица:\n", m_idnt)
print("Диагональная матрица:\n", m_diag)
print("Сумма элементов единичной матрицы:", sum_idnt)
print("Сумма элементов диагональной матрицы:", sum_diag)

if sum_idnt > sum_diag:
    print("Сумма элементов единичной матрицы больше.")
elif sum_idnt < sum_diag:
    print("Сумма элементов диагональной матрицы больше.")
else:
    print("Суммы элементов матриц равны.")


Единичная матрица:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Диагональная матрица:
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма элементов единичной матрицы: 4.0
Сумма элементов диагональной матрицы: 50
Сумма элементов диагональной матрицы больше.


## Задание 6 практической работы
Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. 
Вычислите и выведите: Их сумму, Их разность, Их поэлементное произведение.

In [3]:
import numpy as np

np.random.seed(42)
arr1 = np.random.randint(1, 21, (3, 3))
arr2 = np.random.randint(1, 21, (3, 3))

matrix_sum = arr1 + arr2
matrix_diff = arr1 - arr2
matrix_product = arr1 * arr2

print("Первая матрица:\n", arr1)
print("Вторая матрица:\n", arr2)
print("Сумма матриц:\n", matrix_sum)
print("Разность матриц:\n", matrix_diff)
print("Поэлементное произведение:\n", matrix_product)


Первая матрица:
 [[ 7 20 15]
 [11  8  7]
 [19 11 11]]
Вторая матрица:
 [[ 4  8  3]
 [ 2 12  6]
 [ 2  1 12]]
Сумма матриц:
 [[11 28 18]
 [13 20 13]
 [21 12 23]]
Разность матриц:
 [[ 3 12 12]
 [ 9 -4  1]
 [17 10 -1]]
Поэлементное произведение:
 [[ 28 160  45]
 [ 22  96  42]
 [ 38  11 132]]


## Задание 7 практической работы
Создайте две матрицы NumPy: 
•	Первую размером 2×3, заполненную случайными числами от 1 до 10.
•	Вторую размером 3×2, заполненную случайными числами от 1 до 10.
Выполните матричное умножение ( @ или np.dot ) и выведите результат.


In [5]:
import numpy as np

np.random.seed(42)
arr1 = np.random.randint(1, 11, (2, 3))
arr2 = np.random.randint(1, 11, (3, 2))

matrix_product = arr1 @ arr2

print("Первая матрица (2×3):\n", arr1)
print("Вторая матрица (3×2):\n", arr2)
print("Результат матричного умножения (2×2):\n", matrix_product)


Первая матрица (2×3):
 [[ 7  4  8]
 [ 5  7 10]]
Вторая матрица (3×2):
 [[3 7]
 [8 5]
 [4 8]]
Результат матричного умножения (2×2):
 [[ 85 133]
 [111 150]]


## Задание 8 практической работы
Создайте случайную квадратную матрицу 3×3. Найдите и выведите:
•	Определитель этой матрицы
•	Обратную матрицу (если существует, иначе выведите сообщение, что матрица вырождена)
Используйте функции np.linalg.det и np.linalg.inv.


In [7]:
import numpy as np

np.random.seed(42)
matrix = np.random.randint(1, 11, (3, 3))

# Определитель
determinant = np.linalg.det(matrix)

# Обратная матрица
if np.isclose(determinant, 0):
    inverse_matrix = "Матрица вырождена, обратной матрицы не существует."
else:
    inverse_matrix = np.linalg.inv(matrix)


print("Исходная матрица:\n", matrix)
print("Определитель матрицы:", determinant)
print("Обратная матрица:\n", inverse_matrix)


Исходная матрица:
 [[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]]
Определитель матрицы: -26.000000000000014
Обратная матрица:
 [[ 0.53846154 -0.92307692  0.61538462]
 [ 0.38461538 -1.23076923  1.15384615]
 [-0.53846154  1.42307692 -1.11538462]]


## Задание 9 практической работы
Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от 1 до 50. Выведите:
•	Исходную матрицу
•	Транспонированную матрицу
•	След матрицы (сумму элементов на главной диагонали)
Используйте np.trace для нахождения следа.


In [9]:
import numpy as np

np.random.seed(42)
matrix = np.random.randint(1, 51, (4, 4))

transposed_matrix = matrix.T

trace_value = np.trace(matrix)

print("Исходная матрица:\n", matrix)
print("Транспонированная матрица:\n", transposed_matrix)
print("След матрицы:", trace_value)

Исходная матрица:
 [[39 29 15 43]
 [ 8 21 39 19]
 [23 11 11 24]
 [36 40 24  3]]
Транспонированная матрица:
 [[39  8 23 36]
 [29 21 11 40]
 [15 39 11 24]
 [43 19 24  3]]
След матрицы: 74


## Задание 10 практической работы
Решите систему линейных уравнений вида:
[2, 3, -1]
[4, -1, 2]
[-3, 5, 4]
Используйте матричное представление Ax = B , где A – матрица коэффициентов, x – вектор неизвестных, B – вектор правой части. 
Решите систему с помощью np.linalg.solve и выведите результат.


In [11]:
import numpy as np

A = np.array([[2, 3, -1],
              [4, -1, 2],
              [-3, 5, 4]])

B = np.array([5, 6, -2])

solution = np.linalg.solve(A, B)

print("Решение системы (x, y, z):", solution)


Решение системы (x, y, z): [1.63963964 0.57657658 0.00900901]


## Задание 11 практической работы
Каждое задание предусматривает построение системы линейных уравнений. 
Решите полученную систему уравнений с использованием библиотеки NumPy. 
Для решения системы используйте метод Крамера и матричный метод. 
Сравните полученные результаты, с результатами, полученными с помощью np.linalg.solve .
### Вариант 6. Распределение воды по трубам. 
Вода поступает в три резервуара из общей системы труб. 
В первый резервуар поступает в два раза больше воды, чем во второй, а в третий — на 50 литров больше, чем во второй. 
Всего в систему поступает 500 литров воды. 
Сколько воды поступает в каждый резервуар?

In [19]:
import numpy as np

# x - первый резервуар, y - второй резервуар, z - третий резервуар

A = np.array([[1, -2, 0],
              [0, -1, 1],
              [1, 1, 1]])

B = np.array([0, 50, 500])

solution_matrix = np.linalg.solve(A, B)

# Метод Крамера
det_A = np.linalg.det(A)
# Определители для метода Крамера
A1 = A.copy()
A1[:, 0] = B
det_A1 = np.linalg.det(A1)

A2 = A.copy()
A2[:, 1] = B
det_A2 = np.linalg.det(A2)

A3 = A.copy()
A3[:, 2] = B
det_A3 = np.linalg.det(A3)

x_kramer = det_A1 / det_A
y_kramer = det_A2 / det_A
z_kramer = det_A3 / det_A

solution_kramer = np.array([x_kramer, y_kramer, z_kramer])


print("Решение методом матриц (np.linalg.solve):", solution_matrix)
print("Решение методом Крамера:", solution_kramer)


Решение методом матриц (np.linalg.solve): [225.  112.5 162.5]
Решение методом Крамера: [225.  112.5 162.5]
